import { ToastContainer } from "react-toastify";
import { Providers } from "./providers";
import { Work_Sans, Space_Mono } from "next/font/google";
import { BaseLayout } from "./layouts/base-layout";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});
const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${workSans.variable} ${spaceMono.variable}`}>
      <body>
        <Providers>
          <BaseLayout>{children}</BaseLayout>
          <ToastContainer theme="dark" />
        </Providers>
      </body>
    </html>
  );
}
